name: run-demo
on:
  workflow_dispatch:
    inputs:
      key:
        type: string
        description: lightrun-api-key
jobs:
  dotnet-run:
      runs-on: ubuntu-latest
      timeout-minutes: 30
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Compile Code
          run: bash build.sh
        - name: Run Code
          run: LIGHTRUN_KEY=${{ github.event.inputs.key }} bash run.sh

